// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVT_pteBlv38eL0_c_pKbbRq-IT0A_4Xs',
    appId: '1:981583881750:web:ea3dfbd48c9be9d3857737',
    messagingSenderId: '981583881750',
    projectId: 'mubwara',
    authDomain: 'mubwara.firebaseapp.com',
    storageBucket: 'mubwara.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOAxxoSGgKc1XkK1JiOVX2DaRSDaxhsRQ',
    appId: '1:981583881750:android:21a03c44111876c2857737',
    messagingSenderId: '981583881750',
    projectId: 'mubwara',
    storageBucket: 'mubwara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE9S5F43jHXkabJJ034_0_KBu15ec66VM',
    appId: '1:981583881750:ios:9886808eb3d26f48857737',
    messagingSenderId: '981583881750',
    projectId: 'mubwara',
    storageBucket: 'mubwara.appspot.com',
    iosClientId: '981583881750-q4lbcetbqklitsl973ja2msgji4s4enc.apps.googleusercontent.com',
    iosBundleId: 'site.metacoding.mubwara',
  );
}
